services:
  # Web Service
  - type: web
    name: focusedroom-web
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: cd 02_FocusedRoom_website && pip install -r requirements.txt
    startCommand: cd 02_FocusedRoom_website && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 run:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: focusedroom-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: your-email@gmail.com
      - key: MAIL_PASSWORD
        value: your-app-password
      - key: MAIL_DEFAULT_SENDER
        value: your-email@gmail.com
      - key: GEMINI_API_KEY
        value: your-gemini-api-key

databases:
  - name: focusedroom-db
    databaseName: focusedroom
    plan: free
    region: oregon
