# Pre-commit hooks for Focused Room Website
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.13
        args: [--line-length=100]

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # Linting with Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --extend-ignore=E203,W503]

  # Linting with Ruff (faster alternative)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Prevent large files from being committed
      - id: check-added-large-files
        args: [--maxkb=1000]

      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict

      # Ensure files end with newline
      - id: end-of-file-fixer

      # Trim trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Check JSON files for syntax errors
      - id: check-json

      # Check YAML files for syntax errors
      - id: check-yaml

      # Check TOML files for syntax errors
      - id: check-toml

      # Prevent committing to main branch
      - id: no-commit-to-branch
        args: [--branch=main]

      # Check for merge conflict markers
      - id: check-merge-conflict

      # Check for debugger imports
      - id: debug-statements

      # Detect private keys
      - id: detect-private-key

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-requests]

  # Security checks with Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [-r, app/]
        exclude: tests/

# Configuration
default_language_version:
  python: python3.13

# Skip certain hooks for specific files
exclude: |
  (?x)^(
      __pycache__/|
      \.git/|
      \.venv/|
      venv/|
      env/|
      instance/|
      \.pytest_cache/
  )$
